/** Mapeamento de nomes/abreviações → OSIS ID (Move Reino Bible) */
export const OSIS_BOOK_MAP: Record<string, string> = {
  Genesis: "Gen",
  Gen: "Gen",
  Gn: "Gen",
  Gênesis: "Gen",
  Exodus: "Exod",
  Exod: "Exod",
  Ex: "Exod",
  Êxodo: "Exod",
  Leviticus: "Lev",
  Lev: "Lev",
  Levítico: "Lev",
  Numbers: "Num",
  Num: "Num",
  Números: "Num",
  Deuteronomy: "Deut",
  Deut: "Deut",
  Deuteronomio: "Deut",
  Deuteronômio: "Deut",
  Joshua: "Josh",
  Josh: "Josh",
  Josué: "Josh",
  Judges: "Judg",
  Judg: "Judg",
  Juízes: "Judg",
  Ruth: "Ruth",
  Rute: "Ruth",
  "1 Samuel": "1Sam",
  "1Sam": "1Sam",
  "1 Sam": "1Sam",
  "2 Samuel": "2Sam",
  "2Sam": "2Sam",
  "1 Kings": "1Kgs",
  "1Kgs": "1Kgs",
  "1 Kgs": "1Kgs",
  "2 Kings": "2Kgs",
  "2Kgs": "2Kgs",
  "1 Chronicles": "1Chr",
  "1Chr": "1Chr",
  "1 Chr": "1Chr",
  "2 Chronicles": "2Chr",
  "2Chr": "2Chr",
  Ezra: "Ezra",
  Nehemiah: "Neh",
  Neh: "Neh",
  Neemias: "Neh",
  Esther: "Esth",
  Ester: "Esth",
  Job: "Job",
  Jó: "Job",
  Psalms: "Ps",
  Psalm: "Ps",
  Ps: "Ps",
  Salmos: "Ps",
  Proverbs: "Prov",
  Prov: "Prov",
  Provérbios: "Prov",
  Ecclesiastes: "Eccl",
  Eccl: "Eccl",
  Eclesiastes: "Eccl",
  "Song of Solomon": "Song",
  Song: "Song",
  Cantares: "Song",
  Isaiah: "Isa",
  Isa: "Isa",
  Isaías: "Isa",
  Jeremiah: "Jer",
  Jer: "Jer",
  Jeremias: "Jer",
  Lamentations: "Lam",
  Lam: "Lam",
  Lamentações: "Lam",
  Ezekiel: "Ezek",
  Ezek: "Ezek",
  Ezequiel: "Ezek",
  Daniel: "Dan",
  Dan: "Dan",
  Hosea: "Hos",
  Hos: "Hos",
  Oseias: "Hos",
  Joel: "Joel",
  Jol: "Joel",
  Amos: "Amos",
  Obadiah: "Obad",
  Obad: "Obad",
  Obadias: "Obad",
  Jonah: "Jonah",
  Jon: "Jonah",
  Jonas: "Jonah",
  Micah: "Mic",
  Mic: "Mic",
  Miquéias: "Mic",
  Nahum: "Nah",
  Nah: "Nah",
  Naum: "Nah",
  Habakkuk: "Hab",
  Hab: "Hab",
  Habacuque: "Hab",
  Zephaniah: "Zeph",
  Zeph: "Zeph",
  Sofonias: "Zeph",
  Haggai: "Hag",
  Hag: "Hag",
  Ageu: "Hag",
  Zechariah: "Zech",
  Zech: "Zech",
  Zacarias: "Zech",
  Malachi: "Mal",
  Mal: "Mal",
  Malaquias: "Mal",
  Matthew: "Matt",
  Matt: "Matt",
  Mateus: "Matt",
  Mark: "Mark",
  Mar: "Mark",
  Marcos: "Mark",
  Luke: "Luke",
  Luk: "Luke",
  Lucas: "Luke",
  John: "John",
  Joh: "John",
  Jo: "John",
  João: "John",
  Acts: "Acts",
  Atos: "Acts",
  Romans: "Rom",
  Rom: "Rom",
  Romanos: "Rom",
  "1 Corinthians": "1Cor",
  "1Cor": "1Cor",
  "1 Cor": "1Cor",
  "2 Corinthians": "2Cor",
  "2Cor": "2Cor",
  Galatians: "Gal",
  Gal: "Gal",
  Gálatas: "Gal",
  Ephesians: "Eph",
  Eph: "Eph",
  Efésios: "Eph",
  Philippians: "Phil",
  Phil: "Phil",
  Filipenses: "Phil",
  Colossians: "Col",
  Col: "Col",
  Colossenses: "Col",
  "1 Thessalonians": "1Thess",
  "1Thess": "1Thess",
  "1 Thess": "1Thess",
  "2 Thessalonians": "2Thess",
  "2Thess": "2Thess",
  "1 Timothy": "1Tim",
  "1Tim": "1Tim",
  "2 Timothy": "2Tim",
  "2Tim": "2Tim",
  Titus: "Titus",
  Tit: "Titus",
  Tito: "Titus",
  Philemon: "Phlm",
  Phlm: "Phlm",
  Filemom: "Phlm",
  Hebrews: "Heb",
  Heb: "Heb",
  Hebreus: "Heb",
  James: "Jas",
  Jas: "Jas",
  Tiago: "Jas",
  "1 Peter": "1Pet",
  "1Pet": "1Pet",
  "1 Pe": "1Pet",
  "2 Peter": "2Pet",
  "2Pet": "2Pet",
  "1 John": "1John",
  "1John": "1John",
  "1 Jn": "1John",
  "2 John": "2John",
  "2John": "2John",
  "3 John": "3John",
  "3John": "3John",
  Jude: "Jude",
  Judas: "Jude",
  Revelation: "Rev",
  Rev: "Rev",
  Apocalypse: "Rev",
  Apocalipse: "Rev",
};

export function resolveOsisBook(book: string): string | null {
  const trimmed = book.trim();
  if (!trimmed) return null;
  if (OSIS_BOOK_MAP[trimmed]) return OSIS_BOOK_MAP[trimmed];

  const normalized = trimmed.replace(/\s+/g, " ");
  if (OSIS_BOOK_MAP[normalized]) return OSIS_BOOK_MAP[normalized];

  const noAccent = normalized
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  for (const [key, osis] of Object.entries(OSIS_BOOK_MAP)) {
    const keyNorm = key.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (keyNorm.toLowerCase() === noAccent.toLowerCase()) return osis;
  }

  const compact = trimmed.replace(/\./g, "").replace(/\s/g, "");
  for (const [key, osis] of Object.entries(OSIS_BOOK_MAP)) {
    if (key.replace(/\s/g, "").toLowerCase() === compact.toLowerCase()) return osis;
  }

  return null;
}
